version: '3'

services:

  monitoring_portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"

  web_commander:
    build: ./web/Commander
    ports:
      - "1337:80"
  web_commander2:
    build: ./web/Commander2
    ports:
      - "1338:80"
  web_commander3:
    build: ./web/Commander3
    ports:
      - "1339:80"
  web_commander4:
    build: ./web/Commander4
    ports:
      - "1340:80"
  web_commander5:
    build: ./web/Commander5
    ports:
      - "1341:80"
  web_truthy:
    build: ./web/truthy
    ports:
      - "1342:80"
  web_niftyhashing:
    build: ./web/NiftyHashing
    ports:
      - "1344:80"
  web_extraction:
    build: ./web/GlobalEXTRACTion
    ports:
      - "1345:80"
  web_captcha:
    build: ./web/CaptchyCaptcha
    ports:
      - "1346:80"
  bank:
    build: ./web/BankOfWhitehacks
    ports:
      - "1347:80"


  pwn_bof:
    build:
      context: .
      dockerfile: ./Dockerfile-pwn
      args:
        - BINARY=bof
        - BINARY_DIR=./pwn/bof
        - DISABLE_ASLR=true
    ports:
      - "1300:9999"
  pwn_bof1:
    build:
      context: .
      dockerfile: ./Dockerfile-pwn
      args:
        - BINARY=bof1
        - BINARY_DIR=./pwn/bof1
    ports:
      - "1301:9999"
  pwn_bof2:
    build:
      context: .
      dockerfile: ./Dockerfile-pwn
      args:
        - BINARY=bof2
        - BINARY_DIR=./pwn/bof2
    ports:
      - "1302:9999"
  pwn_bof3:
    build:
      context: .
      dockerfile: ./Dockerfile-pwn
      args:
        - BINARY=bof3
        - BINARY_DIR=./pwn/bof3
    ports:
      - "1303:9999"
  pwn_ezprintf:
    build:
      context: .
      dockerfile: ./Dockerfile-pwn
      args:
        - BINARY=ezprintf
        - BINARY_DIR=./pwn/ezprintf
    ports:
      - "1304:9999"

  crypto_residues:
    build:
      context: .
      dockerfile: ./Dockerfile-crypto
      args:
        - CRYPTO_DIR=./crypto/Residues
    ports:
      - "1400:9999"
  crypto_aes_rsa:
    build:
      context: .
      dockerfile: ./Dockerfile-crypto
      args:
        - CRYPTO_DIR=./crypto/AES-RSA
    ports:
      - "1401:9999"

volumes:
  portainer_data:
